let a = 10;
let b = 13;
console.log("Decrement : " , (a+b)); 
console.log("Substraction : " , (a-b));
console.log("Multiplication : " , (a*b));
console.log("Division : " , (a/b));
console.log("Remainder : " , (a%b));
console.log("Increment : " , (a++));
console.log("Decrement : " , (b--));
console.log("Exponentiation : " , (a**b));
